server:
  port: 8082

spring:
  # mysql数据库配置
  datasource:
    name: sakila
    url: jdbc:mysql://192.168.169.129:3306/sakila?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 10
      min-idle: 10
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

  #发邮件配置
  mail:
    host: smtp.126.com
    username: lwk_mail@126.com
    password: liuweikang1900
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    # 日志中显示sql语句
    show-sql: true
    hibernate:
      # 自动更新
      ddl-auto: update
  # redis配置
  redis:
    host: 192.168.169.129
    password: 123456
    port: 6379
    database: 0
    timeout: 10000
    jedis:
      pool:
        max-idle: 200
        max-wait: 500
        max-active: 1000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 50MB
  # 线程池配置
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
  # mongodb 配置
  data:
    mongodb:
      host: 192.168.169.133
      port: 27017
      database: test

# 监控关闭
management:
  security:
    enabled: false

# log4j2，暂时一个文件（可以分环境配置不同xml）
logging:
  config: classpath:log4j2.xml

# 是否开启swagger，正式环境一般是需要关闭的，可根据springboot的多环境配置进行设置
swagger:
  enabled: true

zk:
  zkServer: "10.240.169.114:2181"
  sessionTimeoutMs: 10000
  baseSleepTimeMs: 1000
  maxRetries: 5

